<?php
// Call QA_Peardoc_Coverage_ClassListTest::main() if this source file is executed directly.
if (!defined("PHPUnit2_MAIN_METHOD")) {
    define("PHPUnit2_MAIN_METHOD", "QA_Peardoc_Coverage_ClassListTest::main");
}

require_once "PHPUnit2/Framework/TestCase.php";
require_once "PHPUnit2/Framework/TestSuite.php";

// You may remove the following line when all tests have been implemented.
require_once "PHPUnit2/Framework/IncompleteTestError.php";

require_once "QA/Peardoc/Coverage/ClassList.php";
require_once dirname(__FILE__) . '/config.php';

/**
 * Test class for QA_Peardoc_Coverage_ClassList.
 * Generated by PHPUnit2_Util_Skeleton on 2006-10-18 at 12:28:36.
 */
class QA_Peardoc_Coverage_ClassListTest extends PHPUnit2_Framework_TestCase {
    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main() {
        require_once "PHPUnit2/TextUI/TestRunner.php";

        $suite  = new PHPUnit2_Framework_TestSuite("QA_Peardoc_Coverage_ClassListTest");
        $result = PHPUnit2_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, open a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp() {
        $this->strPearDir = $GLOBALS['testConfig']['PearDir'];
        $this->assertTrue(file_exists($this->strPearDir));
        $this->assertTrue(is_dir($this->strPearDir));
    }

    /**
     * Tears down the fixture, for example, close a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown() {
    }



    public function testAuth()
    {
        $strAuthDir = $this->strPearDir . '/Auth';
        $this->assertTrue(file_exists($strAuthDir));
        $ar = QA_Peardoc_Coverage_ClassList::getClassList($strAuthDir, false);

        $this->assertNotEquals(0, count($ar));
        $this->assertTrue(in_array('Auth.php', $ar));
        $this->assertTrue(in_array('Auth/Auth.php', $ar));
        $this->assertTrue(in_array('Container/Array.php', $ar));
        $this->assertFalse(in_array('tests/DBContainer.php', $ar));
    }//public function testAuth()

}

// Call QA_Peardoc_Coverage_ClassListTest::main() if this source file is executed directly.
if (PHPUnit2_MAIN_METHOD == "QA_Peardoc_Coverage_ClassListTest::main") {
    QA_Peardoc_Coverage_ClassListTest::main();
}
?>